name: Run ADO to GitHub Sync with PowerShell

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v3
      - run: |
           $ListObject = GC -Path "$($env:GITHUB_WORKSPACE)\ADORepoList.json" | ConvertFrom-Json
           foreach ($object in $ListObject.RepoList){
            write-host "--------------- Current syncing for repo $($object.TODOIntake4)----------------------------------"
            Set-Location $($env:GITHUB_WORKSPACE)
             .\SynADOtoGitHub.ps1 -GitHubDestinationPAT ${{ secrets.GITHUBDESTINATIONPAT }} -ADOSourcePAT ${{ secrets.ADOSOURCEPAT }} -AzureRepoName $($object.TODOIntake4)
            write-host "---------------------------------------------------------------------------------------------------"
           }
